### ISSUE TITLE
Some delivery attachment fail to be uploaded

### ISSUE THREAD

**Issue by JWGmeligMeyling** [devhub-tud/devhub#408]
```
java.lang.IllegalArgumentException: Failure parsing MediaType string: application/text-plain:formatted
	at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.parse(MediaTypeHeaderDelegate.java:135) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.delegates.MediaTypeHeaderDelegate.fromString(MediaTypeHeaderDelegate.java:18) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at javax.ws.rs.core.MediaType.valueOf(MediaType.java:179) ~[jaxrs-api-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.multipart.MultipartInputImpl$PartImpl.<init>(MultipartInputImpl.java:253) ~[resteasy-multipart-provider-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.multipart.MultipartInputImpl.extractPart(MultipartInputImpl.java:234) ~[resteasy-multipart-provider-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataInputImpl.extractPart(MultipartFormDataInputImpl.java:64) ~[resteasy-multipart-provider-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.multipart.MultipartInputImpl.extractParts(MultipartInputImpl.java:229) ~[resteasy-multipart-provider-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.multipart.MultipartInputImpl.parse(MultipartInputImpl.java:198) ~[resteasy-multipart-provider-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataReader.readFrom(MultipartFormDataReader.java:52) ~[resteasy-multipart-provider-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataReader.readFrom(MultipartFormDataReader.java:20) ~[resteasy-multipart-provider-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:59) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.interception.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:62) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:51) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPDecodingInterceptor.aroundReadFrom(GZIPDecodingInterceptor.java:59) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:150) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:89) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:112) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) ~[resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) [resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) [resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) [resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.0.10.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.0.10.Final.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [jetty-servlet-9.2.10.v20150310.jar:9.2.10.v20150310]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89) [guice-servlet-4.0.jar:na]
```

**Comment by JWGmeligMeyling** [comment]
> Had the same problem with a .svg file.
> 
> Solved it by modifying the Mozilla Firefox mimeTypes.rdf file in the profile folder. (thx to Piotrs Link above)
> 
> For other people having a similar problem. This was caused due to a mistakenly set Content-Type in my PHP script. When first testing the script (it delivered a svg file indirectly via php) i had another Content-Type set in the header().
> 
> `header("Content-Type: image/svg+xml"); //should have been`
> `header("Content-Type: application/vnd.android.package-archive"); //was actually set`
> 
> This now overruled the content type setting in the firefox `mimeTypes.rdf` file:
> 
>```
  <RDF:Description RDF:about="urn:mimetype:application/vnd.android.package-archive"
                   NC:value="application/vnd.android.package-archive"
                   NC:editable="true"
                   NC:fileExtensions="svg"
                   NC:description="Scalable Vector Graphics">
    <NC:handlerProp RDF:resource="urn:mimetype:handler:application/vnd.android.package-archive"/>
  </RDF:Description>
> ```
> Probably because FF thinks its seeing a "new" file/filetype - and adding it to its config.
> 
> To fix this, you only need to delete the wrong XML section in the mimeTypes.rdf and restart FF of course.

http://stackoverflow.com/a/15300874/2104280
